### PR TITLE
Unit test modules/blocks/api

### PR DESCRIPTION
**Pull request by roman-bystrimovich**

### CODE REVIEW

**Review by vekexasia — CHANGES_REQUESTED** [review]
Please remove duplicated tests lines to proper test case before the others as discussed in pm

**Comment by vekexasia** [comment]
@roman-bystrimovich There are 2 tests which are *long* does they really need to be that long or can we split into multiple tests  (or move some code into before hooks?

**Comment by roman-bystrimovich** [comment]
@vekexasia I got rid of duplicated function call tests.

**Review by vekexasia — APPROVED** [review]

**Comment by vekexasia** [comment]
Perfect :+1: @roman-bystrimovich thanks.

**Pull request merged**
